<?php
/**
 * is a personage but got magic
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        Personage
 */
require_once('Personage.class.php');

class Magician extends Personage {

	/**
	 * is like mana
	 * @var int
	 * @access public
	 */
	public  $magic = 10;


}
?>