<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

abstract class Personage implements iMovable {

	/**
	 * personage id (unique)
	 * @var int
	 * @access protected
	 */
	protected  $id;

	/**
	 * personage name
	 * @var string
	 * @access protected
	 */
	protected  $name;

	/**
	 * personage strength
	 * @var int
	 * @access protected
	 */
	protected  $strength = 10;
	const DEFAULT_STRENGTH = 10;


	/**
	 * used to set attributes like a constructor but it is not because not called when instantiate
	 * @access public
	 * @param string $name define personage name
	 * @param int $strength define personage strength
	 * @return void
	 */

	public final  function set($name, $strength) {

	}


	/**
	 * return name attribute
	 * @access public
	 * @return string
	 */

	public final  function getName() {

	}


}
?>